version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nbduser
      MONGO_INITDB_ROOT_PASSWORD: nbdpass
      MONGO_INITDB_DATABASE: VMDB

volumes:
  mongodb_data: